name: Deploy Docs

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Install mkdocs-material using pip
        shell: bash -l {0}
        run: pip install mkdocs-material

      - name: Test that docs build without error
        shell: bash -l {0}
        if: github.event_name == 'pull_request'
        run: mkdocs build --strict

      - name: Deploy docs to GitHub Pages
        shell: bash -l {0}
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --strict --force

